# This is a basic workflow to help you get started with Actions

name: Send Mail Everyday

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: 1.17.9

      - name: Run everyday job
        run: |
          go run main.go
          
      - name: Push to github
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          add: 'output/'
          message: "generate output html"
          
      - name: Send Mail
        uses: betterfor/action-send-mail@v0.1.0
        with:
          # 必需，邮件服务器地址
          server_address: smtp.qq.com
          # 必需，邮件服务器端口，默认25 (如果端口为465，则会使用TLS连接)
          server_port: 465
          # 可选 (建议): 邮件服务器用户
          username: ${{secrets.MAIL_USERNAME}}
          # 可选 (建议): 邮件服务器密码
          password: ${{secrets.MAIL_PASSWORD}}
          # 必需，邮件主题
          subject: 一封暖暖的邮件
          # 必需，收件人地址
          to: ${{secrets.MAIL_TO}}
          # 必需，发送人全名 (地址可以省略)
          from: betterfor # <alice@example.com>
          # 可选，HTML内容，可从文件读取
          html_body: file://output/output.html
